tunnel: 2796561e-db08-4826-82ad-6ef6b737f5bf

ingress:
  - hostname: www.regilearn.online
    service: http://student-course-registration-deployment.default.svc.cluster.local:5000
  - hostname: local.regilearn.online
    service: http://192.168.49.2:32712
  - service: http_status:404