apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-course-registration-deployment
  labels:
    app: student-course-registration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-course-registration
  template:
    metadata:
      labels:
        app: student-course-registration
    spec:
      containers:
        - name: student-course-registration
          image: gaga730/student-course-registration:latest
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_HOST
              value: "mysql-service"   # 👈 match Service name
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "2005"
            - name: MYSQL_DB
              value: "student_db"