apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-course-registration-deployment
  labels:
    app: student-course-registration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-course-registration
  template:
    metadata:
      labels:
        app: student-course-registration
    spec:
      containers:
        - name: student-course-registration
          image: docker.io/gaga730/student-course-registration:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"