apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: Nodeport
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 80           # Public-facing port
      targetPort: 8080   # Jenkins container port